--DROP DATABASE IF EXISTS burgerDB;
--CREATE DATABASE burgerDB;
USE burgerDB;

CREATE TABLE burgers
(
	id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	burgerName VARCHAR(255) NOT NULL,
    devoured BOOLEAN DEFAULT false
); 